// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package repository

import (
	armresources "github.com/Azure/azure-sdk-for-go/sdk/resources/armresources"
	mock "github.com/stretchr/testify/mock"
)

// mockArmResourcesClient is an autogenerated mock type for the armResourcesClient type
type mockArmResourcesClient struct {
	mock.Mock
}

// List provides a mock function with given fields: options
func (_m *mockArmResourcesClient) List(options *armresources.ResourceGroupsListOptions) armResourcesListPager {
	ret := _m.Called(options)

	var r0 armResourcesListPager
	if rf, ok := ret.Get(0).(func(*armresources.ResourceGroupsListOptions) armResourcesListPager); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(armResourcesListPager)
		}
	}

	return r0
}
